add-routing-to-concept-map-from-assignment
COSC447-Directed-Studies/canvas-gamification-ui pull request #45
Opened 2023-02-09 21:59 UTC by SamamthaH

## Description

Describe your changes in detail

Moved error messages such as the 'this event-type is closed' above the event name. If there are no questions in the event, displays a bolded instruction and link to concept map to add questions underneath the message informing the user of the lack of questions. If there are questions, added same message in the instruction text font used in the first layer of the question bank tab. Added css to change the colour of the word "concept map" to highlight that it is a link.

## Types of changes

What types of changes does your code introduce?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (only improve the code quality no change in functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] Issue has been created
- [x] Every file touched is linted
- [ ] Every file touched has tests that cover all the funcitonality with green coverage
- [ ] Documentation is updated (if applicable).

## Issue

Please link the issue here.
https://github.com/COSC447-Directed-Studies/canvas-gamification-ui/issues/44

## Tests

Please describe in detail what tests you added or changed.

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/79422004/217948774-cac291f8-e39d-437d-948a-07b828b0fe9b.png)
![image](https://user-images.githubusercontent.com/79422004/217948837-04d19f2a-4634-464c-b47e-aef5410afc44.png)

2023-02-11 20:10 UTC, keyvankhademi requested changes

2023-02-11 20:10 UTC, keyvankhademi commented on src/app/course/course-question-snippet/course-question-snippet.component.html
> +                            <a [routerLink]="['../../practice/concepts']" class="colorpls">
colorpls?

2023-02-11 20:10 UTC, keyvankhademi commented on src/app/course/course-question-snippet/course-question-snippet.component.html
> +                        <a [routerLink]="['../../practice/concepts']" class="colorpls">
colorpls?

2023-02-13 06:13 UTC, SamamthaH commented on src/app/course/course-question-snippet/course-question-snippet.component.html
> +                            <a [routerLink]="['../../practice/concepts']" class="colorpls">
whoops, forgot to change that

2023-02-14 17:19 UTC, keyvankhademi approved these changes

2023-02-14 17:19 UTC, merged